#!/bin/bash

CURRENT_NAME=$(whoami)
CURRENT_UID=$(id -u)
CURRENT_GID=$(id -g)


docker run --rm --name=dev -it \
  --hostname=dev \
  -v /datapool/nas/code/bu/cp/go:/gopath \
  -v /datapool/nas/code/bu/cp:/home/brent/code \
  -v $HOME/.gitconfig:/home/brent/.gitconfig \
  -v $HOME/.ssh:/home/brent/.ssh \
  -e POSTGRES_USER=${POSTGRES_USER} \
  -e POSTGRES_PASSWORD=${POSTGRES_PASSWORD} \
  -e POSTGRES_SERVER=${POSTGRES_SERVER} \
  -e POSTGRES_DB=${POSTGRES_DB} \
  -e PLEX_WATCHLIST_BASE_FOLDER=${PLEX_WATCHLIST_BASE_FOLDER} \
  -p 4242:22 \
  -p 4243:8000 \
  -p 2323:8080 \
  energyvault462/dev
