#!/bin/bash

CURRENT_NAME=$(whoami)
CURRENT_UID=$(id -u)
CURRENT_GID=$(id -g)


docker run --rm --name=dev -it \
  --hostname=dev \
  -v /datapool/nas/code/bu/cp/go:/gopath \
  -v /datapool/nas/code/bu/cp:/home/brent/code \
  -v $HOME/.gitconfig:/home/brent/.gitconfig \
  -v $HOME/.ssh:/home/brent/.ssh \
  -p 4242:22 \
  -p 4243:8000 \
  dev
